// Every piece of text shown in the AI panel lives here (the only file to change when re-skinning).
export const labels = {
  title: "AI assistant",
  teacherHint: "Ask about your schedule, or name every enrolled student's attendance status.",
  studentHint: "Ask about your schedule, or about something in your course materials.",
  inputLabel: "Message the assistant",
  inputPlaceholder: "Type a message",
  send: "Send",
  thinking: "Thinking...",
  you: "You",
  assistant: "Kora",
  failure: "Something went wrong. Please try again.",
  pendingRestored: (count: number) =>
    `You have ${count} ${count === 1 ? "change" : "changes"} waiting for your decision. Nothing has been applied yet.`,
  sources: "Sources",
  result: {
    studentAdded: "added to the course",
    studentAlreadyJoined: "was already in the course",
    studentNotRegistered: "no student account with this email, so not added",
    studentFailed: "could not be added",
  },
  dashboard: {
    widgets: {
      STATS: "Week at a glance",
      TODAY_SESSIONS: "Today",
      WEEK_SCHEDULE: "This week",
      MONTH_CALENDAR: "Month calendar",
      PENDING_REQUESTS: "Requests",
      STUDENT_FOCUS: "Student focus",
      ATTENDANCE_TREND: "Attendance trend",
      RECENT_PROGRESS: "Recent progress",
      COURSE_LIST: "My courses",
    },
    themes: { kora: "Kora", ocean: "Ocean", sunset: "Sunset", forest: "Forest", violet: "Violet", midnight: "Midnight" },
    motions: { calm: "Calm", lively: "Lively", off: "No motion" },
    saved: "Home page layout saved and now active",
  },
  knowledge: {
    kinds: { LESSON_SUMMARY: "Lesson summary", KNOWLEDGE_POINT: "Key point", COMMON_MISTAKE: "Common mistake", EXAMPLE: "Example", FAQ: "FAQ", TEACHING_STYLE: "Teaching style" },
    saved: "Teaching notes saved",
  },
  quiz: {
    types: { MULTIPLE_CHOICE: "multiple choice", TRUE_FALSE: "true/false", SHORT_ANSWER: "short answer" },
    levels: { EASY: "easy", MEDIUM: "medium", HARD: "hard" },
    saved: "Quiz saved as a draft",
  },
  proposal: {
    heading: "Review before anything changes",
    notChanged: "Nothing has been changed yet.",
    confirm: "Confirm",
    cancel: "Cancel",
    working: "Working...",
    done: "Done. The change has been applied.",
    discarded: "Cancelled. Nothing was changed.",
    failedPrefix: "Not applied: ",
  },
} as const;
