// Every piece of text shown in the AI panel lives here (the only file to change when re-skinning).
export const labels = {
  title: "AI assistant",
  teacherHint: "Take attendance, write quizzes and notes, or redesign your home page. Try one of these:",
  teacherSuggestions: [
    "What classes do I have this week?",
    "Create a quiz of 8 questions for my course: 5 multiple choice, 2 true/false, 1 short answer",
    "Create teaching notes from the materials of my course",
    "Design my home page with today, my requests and the attendance trend in ocean colours",
    "Do I have any leave requests?",
  ],
  studentHint: "Ask about your schedule, get a topic explained, or ask for leave. Try one of these:",
  studentSuggestions: [
    "What is on my schedule this week?",
    "Explain the key ideas from my course notes",
    "What do my course materials say about the first unit?",
    "I need leave for my next session",
  ],
  inputLabel: "Message the assistant",
  inputPlaceholder: "Type a message",
  send: "Send",
  thinking: "Thinking...",
  you: "You",
  assistant: "Kiro",
  failure: "Something went wrong. Please try again.",
  pendingRestored: (count: number) =>
    `You have ${count} ${count === 1 ? "change" : "changes"} waiting for your decision. Nothing has been applied yet.`,
  sources: "Sources",
  result: {
    studentAdded: "added to the course",
    studentAlreadyJoined: "was already in the course",
    studentNotRegistered: "no student account with this email, so not added",
    studentFailed: "could not be added",
  },
  dashboard: {
    widgets: {
      STATS: "Week at a glance",
      TODAY_SESSIONS: "Today",
      WEEK_SCHEDULE: "This week",
      MONTH_CALENDAR: "Month calendar",
      PENDING_REQUESTS: "Requests",
      STUDENT_FOCUS: "Student focus",
      ATTENDANCE_TREND: "Attendance trend",
      RECENT_PROGRESS: "Recent progress",
      COURSE_LIST: "My courses",
    },
    themes: { kora: "Kiro", ocean: "Ocean", sunset: "Sunset", forest: "Forest", violet: "Violet", midnight: "Midnight" },
    motions: { calm: "Calm", lively: "Lively", off: "No motion" },
    saved: "Home page layout saved and now active",
  },
  courseChat: {
    studentTitle: "Course tutor",
    teacherTitle: "Course assistant",
    emptyStudent: (course: string) => `Ask anything about ${course}. I only use your teacher's notes and this course's materials, and I show where each answer came from.`,
    emptyTeacher: (course: string) => `Ask for a quiz, teaching notes, attendance or schedule for ${course}. Everything stays within this course.`,
    studentSuggestions: [
      "Explain the main ideas of this course in simple words",
      "What are the common mistakes in this course?",
      "Walk me through a worked example",
      "What do my notes say about the first unit?",
    ],
    teacherSuggestions: [
      "Create a quiz of 6 questions for this course: 4 multiple choice, 1 true/false, 1 short answer",
      "Create teaching notes from this course's materials",
      "When is the next class for this course?",
      "How is attendance going in this course?",
    ],
  },
  chat: {
    newChat: "New chat",
    history: "Chats",
    noChats: "Your chats will appear here.",
    loadingChats: "Loading your chats…",
    loadingChat: "Opening the chat…",
    emptyTitle: "What would you like to do?",
    emptyTeacher: "Each chat keeps its own context, so you can run several things side by side.",
    emptyStudent: "Each chat keeps its own context. Start a new one for a new topic.",
    rename: "Rename",
    delete: "Delete",
    deleteConfirm: "Delete this chat? Its messages will be removed. Changes it prepared are not affected.",
    waiting: "Waiting for your decision",
    inputHint: "Enter to send, Shift+Enter for a new line",
    closeHint: "Esc to close",
    notFound: "That chat is no longer available. Starting a new one.",
    historyFailed: "Could not load your chats. Please try again.",
  },
  knowledge: {
    kinds: { LESSON_SUMMARY: "Lesson summary", KNOWLEDGE_POINT: "Key point", COMMON_MISTAKE: "Common mistake", EXAMPLE: "Example", FAQ: "FAQ", TEACHING_STYLE: "Teaching style" },
    saved: "Teaching notes saved",
  },
  quiz: {
    types: { MULTIPLE_CHOICE: "multiple choice", TRUE_FALSE: "true/false", SHORT_ANSWER: "short answer" },
    levels: { EASY: "easy", MEDIUM: "medium", HARD: "hard" },
    saved: "Quiz saved as a draft",
  },
  proposal: {
    heading: "Review before anything changes",
    notChanged: "Nothing has been changed yet.",
    confirm: "Confirm",
    cancel: "Cancel",
    working: "Working...",
    done: "Done. The change has been applied.",
    discarded: "Cancelled. Nothing was changed.",
    failedPrefix: "Not applied: ",
  },
} as const;
